export const Privacy_Policy = [
  {
    heading: "SMARTe Privacy Policy",
    text: "SMARTe Inc. (“collectively known as SMARTe) is the world’s Data-As-A-Service platform for sales and marketing.  We understand that you care about how information about you is used. This privacy policy describes how SMARTe manages personal information collected, received, or maintained. We collect information pertaining to businesses and business people (“Business Information”) and all other types of information through our website and other online services (the “Site”).",
  },
  {
    heading: "SMARTe Website",
    text: "You may access and browse this website without revealing any of your personal information. However, while downloading any of our material which have been developed by our internal Subject Matter Experts OR while subscribing to our blogs/newsletters OR while filling in a demo request form, we may collect your personal information such as your name, phone number or e-mail id that may be necessary to help us provide better customer service and we maintain the highest levels of confidentiality pertaining to your information.",
  },
  {
    heading: "How does SMARTe collect Website Visitor Information?",
    text: "To browse the Website only, you are not required to provide any personal information. However, we may gather non-personally-identifiable information. Similar to many commercial websites, we utilize “cookies” and other technologies to collect non-personally-identifiable information on visitors to the Website. Cookies allow web servers to recognize the computer used to access a website. Cookies store information accessed through your browser to streamline activities on related web sites, and make the online experience easier and more personalized. Information gathered through cookies and web-server log files may include information such as the date and time of visits, the pages viewed, IP addresses, links to/from any page, and time spent at a site.",
  },
  {
    heading: "How does SMARTe collect Customer Information?",
    text: "Visitors to our Site may choose to submit their name, email address and/or other information so that they can learn more about our services, register to take part in a SMARTe-sponsored event, or participate in a survey, contest or sweepstakes, among other things.",
  },
  {
    heading: "How does SMARTe collect Business Information for its Products?",
    text: '"Business Contact Information" means any of the following information as used in connection with an individual’s business or profession: Name, Title, Company Name, Business Email Address, Business phone number, Work address, Public professional profile address, and/or supplementary information such as business role and responsibility designations. Using next-generation focused crawling, SMARTe builds profiles of business people and companies, which we call “Contacts” from different sources including Corporate Websites, Annual Reports, Social Networks, Tradeshows, Conferences, User Groups, Publications, Associations, News Releases, Technical Papers, List Directories, Communities, Blogs, Press Releases, Company Reports, Trade Magazines, Journals, Newsletters, Professional and Social Networking Sites and Search Engines, etc. Once we have collected business Information about a person or company, we combine multiple mentions of the same person or company into a CONTACTS. The resulting master of Contacts (the “MASTER”) is then made available to the users of the Site and our customers and strategic partners.',
  },
  {
    heading: "SMARTe Products and Services",
    text: "SMARTe collects information regarding companies and their employees, including Business Contact Information on company executives, decision makers, and other employees. The information collected is like that which is typically included on online professional profile, a business card, or business email signature etc. including: name, company name, job title, business email address, business phone number, business address, and corporate website URL. SMARTe gathers, verifies, and organizes this data for purposes of licensing such information to SMARTe clients and strategic partners for sales and marketing purposes. SMARTe obtains data for its database from web crawling, first-hand research including telephone interviews, publicly available resources, and third-party licensors. All the business contact information that SMARTe obtains through any of the foregoing means is verified by SMARTe’s technologies and in-house research team, and information that is found to be inaccurate or irrelevant to the purposes of the Services is removed and deleted. SMARTe endeavors to publish highly accurate business contact information on influencers and decision makers and other agents and employees of the companies it profiles.",
  },
  {
    heading: "The General Data Protection Regulation GDPR For EU Residents",
    text: "SMARTe complies with the recent GDPR regulation by processing data along the GDPR norms. Under GDPR there are six grounds to process personal data, these are equally valid. There are two of these which are relevant to our business (direct B2B marketing) they are: consent or legitimate interest. As Recital 47 of the GDPR states that “The processing of personal data for direct marketing purposes may be regarded as carried out for a legitimate interest.” Using legitimate interest as the basis for B2B marketing involves ensuring key conditions are met: “The processing must relate to the legitimate interests of your business or a specified third party, providing that the interests or fundamental rights of the data subject do not override the business’ legitimate interest.” “The processing must be necessary to achieve the legitimate interests of the organization.” Along with the above compliance, SMARTe DOES NOT share personal data with customers / partners, RECORDS all data processing activities, DON’T SOURCE any sensitive information such as religion, political inclinations, gender, age etc., has an EXPLICIT OPT-IN, OPT-OUT process and is proud to be operating for over 15 years without any data breach As a ‘data processor’, SMARTe Inc. follows the following data privacy requirements honoring the GDPR law (Article 13 and 14). SMARTe provides notice to all data subjects as required by GDPR Article 13 or 14, as appropriate, and honors the rights of data subjects provided in Articles 12-23, including the right to be forgotten. SMARTe informs individuals about the collection and use of their personal data, retention periods for the data, and who it will be shared with. This is a key transparency requirement under the GDPR, provides privacy information to individuals at the time of collecting their personal data. When SMARTe obtains personal data from other sources, we provide individuals with privacy information within a reasonable period of obtaining the data and no later than a month. If any EU resident information is sourced in SMARTe database then SMARTe will provide such individual with a notice detailing the information SMARTe has on such person, the purpose for which it will be used, and informing such person of their rights with respect to such information, including the right to know what information SMARTe possesses on them, to correct such information, or to opt out of data collection entirely. Such persons may opt out of the SMARTe database by emailing privacy@smarte.pro. Information we provide to people is concise, transparent, intelligible, easily accessible, and in clear and plain language. We conduct regular review, and where necessary, update our privacy information. If there are any new uses of an individual’s personal data, we make sure to bring it to their attention before we start processing.",
  },
  {
    heading: "Disclosures of Public Profiles",
    text: "We may make any Business Information that our users contribute for inclusion in our Directory, that we collect from public web sources or that we license from third parties available to users of the Site, to our strategic partners and to our customers.",
  },
  {
    heading: "Disclosures to Service Providers",
    text: "SMARTe may from time to time disclose Business Information or other collected information to service providers, solely for providing functions related to our operation of the Site and for no other purpose. For example: SMARTe uses service providers to process credit card payments on our Site. When you use a credit card to pay for SMARTe services, information such as your name, billing address, phone number, email address and credit card Information will be submitted to service providers for verification and to manage any recurring payments. SMARTe uses software hosted by a service provider to provide us with information regarding our visitors’ activities on our Site. When you visit our Site, that service provider may set cookies on our behalf and may receive information about your browsing activity on our Site.",
  },
  {
    heading: "Disclosures for Legal Reasons",
    text: "We may disclose collected information, including Business Information, to a third party if we believe in good faith that such disclosure is necessary or desirable: (i) to comply with lawful requests, subpoenas, search warrants or orders by public authorities, including to meet national security or law enforcement requirements, (ii) to address a violation of the law, (iii) to protect the rights, property or safety of SMARTe, its users or the public, or (iv) to allow SMARTe to exercise its legal rights or respond to a legal claim.",
  },
  {
    heading: "Disclosures to a Buyer of the Company",
    text: "If our company or substantially all of our assets are acquired, or in the event of a merger or bankruptcy, information about you and/or information you provide to SMARTe may be among the transferred assets. You will be notified via email and/or a prominent notice on our Site of any change in ownership or uses of your personal information, as well as any choices you may have regarding your personal information.",
  },
  {
    heading: "Other Disclosures",
    text: "SMARTe Inc. complies with the EU-U.S. Data Privacy Framework (EU-U.S. DPF) and the UK Extension to the EU-U.S. DPF, and the Swiss-U.S. Data Privacy Framework (Swiss-U.S. DPF) as set forth by the U.S. Department of Commerce. SMARTe Inc. has certified to the U.S. Department of Commerce that it adheres to the EU-U.S. Data Privacy Framework Principles (EU-U.S. DPF Principles) with regard to the processing of personal data received from the European Union and the United Kingdom in reliance on the EU-U.S. DPF and the UK Extension to the EU-U.S. DPF. SMARTe Inc. has certified to the U.S. Department of Commerce that it adheres to the Swiss-U.S. Data Privacy Framework Principles (Swiss-U.S. DPF Principles) with regard to the processing of personal data received from Switzerland in reliance on the Swiss-U.S. DPF. If there is any conflict between the terms in this privacy policy and the EU-U.S. DPF Principles and/or the Swiss-U.S. DPF Principles, the Principles shall govern. To learn more about the Data Privacy Framework (DPF) program, and to view our certification, please visit https://www.dataprivacyframework.gov/ SMARTe Inc. is subject to the investigatory and enforcement powers of the Federal Trade Commission (FTC) We would like to inform individuals about the possibility, under certain conditions, for the individual to invoke binding arbitration.",
  },
];
